#include "interfaces/cli/BashCompletionGenerator.hpp"

#include <fmt/format.h>
#include <fmt/ranges.h>

#include <algorithm>
#include <iterator>
#include <span>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include "interfaces/cli/CliSpec.hpp"

namespace chaos::orchestrator::interfaces::cli {

namespace {

// The shell skeleton is appended verbatim, never routed through fmt: it is full
// of braces ({{.ID}}, ${#COMPREPLY[@]}) that would need doubling.
constexpr std::string_view kPrologue = R"BASH(# Bash completion for the `chaos` CLI.
#
# Generated by `chaos completion bash` - do not edit by hand.
#
# Install system-wide:
#   chaos completion bash | sudo tee /etc/bash_completion.d/chaos >/dev/null
# Or load into the current shell:
#   source <(chaos completion bash)

_chaos_container_ids() {
    command docker ps --format '{{.ID}}' 2>/dev/null
}

_chaos_completion() {
    local cur prev words cword
    if type _init_completion >/dev/null 2>&1; then
        _init_completion || return
    else
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword=$COMP_CWORD
    fi

)BASH";

constexpr std::string_view kFinderHead = R"BASH(
    # Find the subcommand: the first word after argv[0] that is neither a
    # global flag nor a global flag's value.
    local cmd="" cmd_index=0 idx
    for ((idx = 1; idx < cword; idx++)); do
        case "${words[idx]}" in
)BASH";

constexpr std::string_view kFinderTail = R"BASH(            -*) ;;
            *)
                cmd="${words[idx]}"
                cmd_index=$idx
                break
                ;;
        esac
    done

    if [[ -z "$cmd" ]]; then
        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "$global_opts" -- "$cur"))
        else
            COMPREPLY=($(compgen -W "$commands" -- "$cur"))
        fi
        return
    fi

    case "$cmd" in
)BASH";

constexpr std::string_view kEpilogue = R"BASH(    esac
}

complete -F _chaos_completion chaos
)BASH";

// Action blocks are stored unindented; appendIndented puts them at the caller's
// nesting depth. mapfile splits on newlines alone, so candidates containing
// spaces survive as one entry -- `COMPREPLY=($(...))` would split them on every
// space. compopt marks the results as paths so bash appends '/' to directories
// and escapes the rest.
constexpr std::string_view kManifestAction =
    R"BASH(mapfile -t COMPREPLY < <(compgen -f -X '!*.json' -o plusdirs -- "$cur")
[[ ${#COMPREPLY[@]} -gt 0 ]] && compopt -o filenames 2>/dev/null
)BASH";

constexpr std::string_view kFilePathAction = R"BASH(mapfile -t COMPREPLY < <(compgen -f -- "$cur")
[[ ${#COMPREPLY[@]} -gt 0 ]] && compopt -o filenames 2>/dev/null
)BASH";

// Nesting depths, in spaces, of the shell constructs the generator emits into.
constexpr std::size_t kFunctionIndent = 4;   // directly inside _chaos_completion
constexpr std::size_t kCaseArmIndent = 12;   // inside a `case "$cmd"` arm
constexpr std::size_t kNestedIfIndent = 16;  // inside an `if` within a case arm

/** Appends every line of an action block to out, each prefixed with indent spaces. */
void appendIndented(std::string& out, std::string_view block, std::size_t indent) {
    const std::string pad(indent, ' ');
    while (!block.empty()) {
        const std::size_t eol = block.find('\n');
        const std::size_t end = (eol == std::string_view::npos) ? block.size() : eol + 1;
        out.append(pad);
        out.append(block.substr(0, end));
        block.remove_prefix(end);
    }
}

[[nodiscard]] std::string joinWords(std::span<const std::string_view> words) {
    return fmt::format("{}", fmt::join(words, " "));
}

[[nodiscard]] std::string joinWords(const std::vector<std::string_view>& words) {
    return fmt::format("{}", fmt::join(words, " "));
}

/** Word list a positional/flag value expands to, or empty when it is not word-based. */
[[nodiscard]] std::string wordSource(ArgKind kind, std::span<const std::string_view> words) {
    switch (kind) {
        case ArgKind::Choice:
            return joinWords(words);
        case ArgKind::ContainerId:
            return "$(_chaos_container_ids)";
        case ArgKind::None:
        case ArgKind::ManifestPath:
        case ArgKind::FilePath:
        case ArgKind::Text:
            break;
    }
    return {};
}

/** Shell block completing a path-valued argument, or empty when not path-valued. */
[[nodiscard]] std::string_view pathAction(ArgKind kind) {
    switch (kind) {
        case ArgKind::ManifestPath:
            return kManifestAction;
        case ArgKind::FilePath:
            return kFilePathAction;
        case ArgKind::None:
        case ArgKind::Choice:
        case ArgKind::ContainerId:
        case ArgKind::Text:
            break;
    }
    return {};
}

/**
 * Long-form option names only. Short forms still parse when typed, but are
 * deliberately not suggested: they add noise without aiding discovery.
 */
[[nodiscard]] std::vector<std::string_view> flagWordsOf(std::span<const FlagSpec> flags) {
    std::vector<std::string_view> words;
    for (const auto& flag : flags) {
        words.push_back(flag.longName);
    }
    return words;
}

/** Emits `if [[ "$prev" == "--flag" ]]; then ...; fi` handlers for value-taking flags. */
void appendFlagValueHandlers(std::string& out, std::span<const FlagSpec> flags, std::size_t indent) {
    const std::string pad(indent, ' ');
    for (const auto& flag : flags) {
        if (flag.argKind == ArgKind::None) {
            continue;
        }
        const std::string words = wordSource(flag.argKind, flag.values);
        const std::string_view action = pathAction(flag.argKind);
        fmt::format_to(std::back_inserter(out), "{}if [[ \"$prev\" == \"{}\" ]]; then\n", pad, flag.longName);
        if (!words.empty()) {
            fmt::format_to(std::back_inserter(out), "{}    COMPREPLY=($(compgen -W \"{}\" -- \"$cur\"))\n", pad, words);
        } else if (!action.empty()) {
            appendIndented(out, action, indent + kFunctionIndent);
        }
        // ArgKind::Text has no candidates: return so the fallback does not
        // re-offer the flag itself as the value.
        fmt::format_to(std::back_inserter(out), "{}    return\n{}fi\n", pad, pad);
    }
}

[[nodiscard]] std::string renderArmBody(const CommandSpec& command) {
    std::string body;
    appendFlagValueHandlers(body, command.flags, kCaseArmIndent);

    const std::vector<std::string_view> flagWords = flagWordsOf(command.flags);
    const std::string flagList = joinWords(flagWords);

    if (command.positionalKind == ArgKind::None) {
        if (!flagWords.empty()) {
            fmt::format_to(std::back_inserter(body), "            COMPREPLY=($(compgen -W \"{}\" -- \"$cur\"))\n",
                           flagList);
        }
        return body;
    }

    const std::string_view action = pathAction(command.positionalKind);
    if (!action.empty()) {
        // Repeatable path positional: offer flags when the word starts with '-'.
        if (flagWords.empty()) {
            appendIndented(body, action, kCaseArmIndent);
            return body;
        }
        fmt::format_to(std::back_inserter(body),
                       "            if [[ \"$cur\" == -* ]]; then\n"
                       "                COMPREPLY=($(compgen -W \"{}\" -- \"$cur\"))\n"
                       "            else\n",
                       flagList);
        appendIndented(body, action, kNestedIfIndent);
        body.append("            fi\n");
        return body;
    }

    const std::string firstSlot = wordSource(command.positionalKind, command.positionalWords);
    if (firstSlot.empty()) {
        return body;
    }
    if (!command.positionalFirstOnly) {
        fmt::format_to(std::back_inserter(body), "            COMPREPLY=($(compgen -W \"{}\" -- \"$cur\"))\n",
                       firstSlot);
        return body;
    }

    // Options are offered only once the user types a leading dash, so the bare
    // suggestion list stays limited to the positional candidates.
    if (flagWords.empty()) {
        fmt::format_to(std::back_inserter(body),
                       "            if [[ $cword -eq $((cmd_index + 1)) ]]; then\n"
                       "                COMPREPLY=($(compgen -W \"{}\" -- \"$cur\"))\n"
                       "            fi\n",
                       firstSlot);
        return body;
    }
    fmt::format_to(std::back_inserter(body),
                   "            if [[ \"$cur\" == -* ]]; then\n"
                   "                COMPREPLY=($(compgen -W \"{}\" -- \"$cur\"))\n"
                   "            elif [[ $cword -eq $((cmd_index + 1)) ]]; then\n"
                   "                COMPREPLY=($(compgen -W \"{}\" -- \"$cur\"))\n"
                   "            fi\n",
                   flagList, firstSlot);
    return body;
}

struct Arm {
    std::string body;
    std::vector<std::string_view> names;
};

[[nodiscard]] std::vector<Arm> buildArms() {
    std::vector<Arm> arms;
    for (const auto& command : kCommands) {
        std::string body = renderArmBody(command);
        auto pos = std::ranges::find_if(arms, [&body](const Arm& arm) { return arm.body == body; });
        if (pos == arms.end()) {
            arms.push_back(Arm{.body = std::move(body), .names = {command.name}});
        } else {
            pos->names.push_back(command.name);
        }
    }
    return arms;
}

[[nodiscard]] std::vector<std::string_view> commandNames() {
    std::vector<std::string_view> names;
    for (const auto& command : kCommands) {
        if (!command.hidden) {
            names.push_back(command.name);
        }
    }
    return names;
}

/** Global option words, plus any command alias spelled as a long option (e.g. "--help"). */
[[nodiscard]] std::vector<std::string_view> globalOptionWords() {
    std::vector<std::string_view> words = flagWordsOf(kGlobalFlags);
    for (const auto& command : kCommands) {
        for (const auto& alias : command.aliases) {
            if (alias.starts_with("--")) {
                words.push_back(alias);
            }
        }
    }
    return words;
}

[[nodiscard]] std::vector<std::string_view> valueTakingGlobalFlagNames() {
    std::vector<std::string_view> names;
    for (const auto& flag : kGlobalFlags) {
        if (flag.argKind != ArgKind::None) {
            names.push_back(flag.longName);
        }
    }
    return names;
}

}  // namespace

std::string generateBashCompletion() {
    std::string out;
    out.reserve(4096);
    out.append(kPrologue);

    fmt::format_to(std::back_inserter(out), "    local commands=\"{}\"\n", joinWords(commandNames()));
    fmt::format_to(std::back_inserter(out), "    local global_opts=\"{}\"\n\n", joinWords(globalOptionWords()));

    appendFlagValueHandlers(out, kGlobalFlags, kFunctionIndent);

    out.append(kFinderHead);
    const auto valueFlags = valueTakingGlobalFlagNames();
    if (!valueFlags.empty()) {
        // An empty case pattern would be a bash syntax error.
        fmt::format_to(std::back_inserter(out), "            {})\n                ((idx++))\n                ;;\n",
                       fmt::join(valueFlags, " | "));
    }
    out.append(kFinderTail);

    for (const auto& arm : buildArms()) {
        if (arm.body.empty()) {
            fmt::format_to(std::back_inserter(out), "        {}) ;;\n", fmt::join(arm.names, " | "));
        } else {
            fmt::format_to(std::back_inserter(out), "        {})\n{}            ;;\n", fmt::join(arm.names, " | "),
                           arm.body);
        }
    }

    out.append(kEpilogue);
    return out;
}

}  // namespace chaos::orchestrator::interfaces::cli
