name: Tests

on:
  push:
    branches:
      - "**"

jobs:
  tests:
    runs-on: ubuntu-24.04
    env:
      CC: clang-18
      CXX: clang++-18
      VCPKG_BINARY_SOURCES: 'clear;x-gha,readwrite'

    steps:
      - name: Export GitHub Actions cache variables
        uses: actions/github-script@v9
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: false

      - name: Install Toolchain (Clang 18 & Headers)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            clang-18 \
            clang-format-18 \
            lld-18 \
            libstdc++-14-dev \
            ninja-build
          
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-18 100

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg and Cache
        uses: lukka/run-vcpkg@11
        with:
          vcpkgGitCommitId: '66c0373dc7fca549e5803087b9487edfe3aca0a1'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.15.0
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Build Web UI
        working-directory: frontend
        run: pnpm install && pnpm run build

      - name: Check formatting
        run: cmake --workflow --preset check-format

      - name: Configure Release
        run: cmake --preset release-linux-clang

      - name: Build
        run: cmake --build --preset release

      - name: Test
        run: ctest --preset test-release
